# Generated by Django 5.0.7 on 2024-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationformapp', '0003_register_evalutor_1_register_evalutor_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
